### ISSUE TITLE
Revise maven repository dependencies

### ISSUE THREAD

**Issue by stonier** [rosjava/rosjava_bootstrap#40]
Revise our maven url sources in the [ros plugin](https://github.com/rosjava/rosjava_bootstrap/blob/indigo/gradle_plugins/src/main/groovy/org/ros/gradle_plugins/RosPlugin.groovy#L21) @talregev is using the list below. I do not believe we need to add the rep.maven.xxx or central.maven.xxx - these should be automatically picked up by `mavenCentral()`. The jfrog is the standout one there - what is in that?

```
rootProject.allprojects {
    repositories {
        maven {
            url "https://github.com/talregev/rosjava_mvn_repo/raw/master/"
        }
        maven {
            url "https://github.com/rosjava/rosjava_mvn_repo/raw/master/"
        }
        maven {
            url "http://central.maven.org/maven2/"
        }
        maven {
            url "https://repo.jfrog.org/artifactory/libs-releases/"
        }
        maven {
            url "https://repo.maven.apache.org/maven2/"
        }
        maven {
            url "https://repo1.maven.org/maven2/"
        }
    }
}
```

**Comment by talregev** [comment]
from jforg we can pull all the jars dependencies:
this dependencies alredy was in ours github maven repository so i added this links that it will update from here and not from github.

http://repo.jfrog.org/artifactory/libs-releases/org/apache/commons/com.springsource.org.apache.commons.codec/
http://repo.jfrog.org/artifactory/libs-releases/org/apache/commons/com.springsource.org.apache.commons.httpclient/
http://repo.jfrog.org/artifactory/libs-releases/org/apache/commons/com.springsource.org.apache.commons.io/
http://repo.jfrog.org/artifactory/libs-releases/org/apache/commons/com.springsource.org.apache.commons.lang/
http://repo.jfrog.org/artifactory/libs-releases/org/apache/commons/com.springsource.org.apache.commons.logging/
http://repo.jfrog.org/artifactory/libs-releases/org/apache/commons/com.springsource.org.apache.commons.net/

in github it found here:
https://github.com/rosjava/rosjava_mvn_repo/tree/master/org/apache/commons

**Comment by talregev** [comment]
it better to switch to apache.directory.studio instead com.springsource.org
like @DmitryDzz has done in his [fix](https://github.com/robot-mitya/rosjava_bootstrap/commit/d7787f5b85967a8e81f0d4e5952b1c5c84f7028f)

i will write down the links again:  
- http://central.maven.org/maven2/org/apache/directory/studio/org.apache.commons.codec/
- http://central.maven.org/maven2/org/apache/directory/studio/org.apache.httpcomponents.httpclient/
- http://central.maven.org/maven2/org/apache/directory/studio/org.apache.commons.io/
- http://central.maven.org/maven2/org/apache/directory/studio/org.apache.commons.lang/
- http://central.maven.org/maven2/org/apache/directory/studio/org.apache.commons.logging/
- http://central.maven.org/maven2/commons-net/commons-net/

i will change that at rosjave_bootstrap and rosjava_core, and i will see if it pass all the tests.

**Comment by stonier** [comment]
Started migration in [rosjava_bootstrap](https://github.com/rosjava/rosjava_bootstrap/commit/1457c852bad8cd1b3ac480f395648ef94c2f1b2f). Will hold off on the others for now till we're sure it's all working.

Also - rosjava_core is a problem - `org.apache.commons.net` isn't in the directory studio group.

**Comment by talregev** [comment]
can you add this links to [manven repository](https://github.com/rosjava/rosjava_mvn_repo)?

**Comment by talregev** [comment]
> Started migration in rosjava_bootstrap.

make sure after that migration, android_core still compile.
I try to do this, and i get an conflict with old jar: com.springsource.org.apache.commons.codec:1.3.0

**Comment by stonier** [comment]
Ah, this thing:

```
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        /opt/android-sdk/build-tools/21.1.2/dx --dex --output /opt/android_core/src/android_core/android_tutorial_pubsub/build/intermediates/dex/release --input-list=/opt/android_core/src/android_core/android_tutorial_pubsub/build/intermediates/tmp/dex/release/inputList.txt
  Error Code:
        2
  Output:

        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Lorg/apache/commons/codec/Decoder;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
```

**Comment by talregev** [comment]
yes :)
need to understand how get rid of this.
I try also compile javaros_core with new jars apache.directory.studio dependencies too but it didn't help.

I think need also to re-create all the messages and rosjava_messages with new dependencies 

can you check it?

If you succeeded that will be great. and you will need to update maven_repository sooner that you thought. can

can you ask @DmitryDzz  how he solve this issue?

**Comment by talregev** [comment]
i added you on gtalk. so if you available to talk ....

**Comment by DmitryDzz** [comment]
I've been watching you 8-)
I didn't try to solve this issue. My project is on hold for a while. I believe I'll come back in a month. Sorry.

**Comment by talregev** [comment]
it ok :)

**Comment by talregev** [comment]
you can close this issue:
https://github.com/rosjava/rosjava_bootstrap/issues/37
